openapi: 3.0.0
info:
  version: "1.0.0"
  title: "Star Wars Planets API"
  description: "An API to manage Star Wars planets information."
servers:
  - url: https://30g56hkr03.execute-api.sa-east-1.amazonaws.com/dev

paths:
  /planets/fetch:
    get:
      summary: "Fetch planets data"
      operationId: "fetchPlanetsData"
      tags:
        - "Planets"
      responses:
        '200':
          description: "Successful response"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Planet'

  /planets:
    get:
      summary: "List all planets"
      operationId: "listPlanets"
      tags:
        - "Planets"
      responses:
        '200':
          description: "Successful response"
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Planet'
    post:
      summary: "Create a new planet"
      operationId: "createPlanet"
      tags:
        - "Planets"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Planet'
      responses:
        '201':
          description: "Planet created successfully"

  /planets/{id}:
    get:
      summary: "Retrieve a specific planet by its ID"
      operationId: "getPlanetById"
      tags:
        - "Planets"
      parameters:
        - name: "id"
          in: "path"
          required: true
          description: "ID of the planet to retrieve"
          schema:
            type: "integer"
      responses:
        '200':
          description: "Successful response"
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Planet'
        '404':
          description: "Planet not found"
    put:
      summary: "Update a specific planet by its ID"
      operationId: "updatePlanetById"
      tags:
        - "Planets"
      parameters:
        - name: "id"
          in: "path"
          required: true
          description: "ID of the planet to update"
          schema:
            type: "integer"
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Planet'
      responses:
        '200':
          description: "Planet updated successfully"
    delete:
      summary: "Delete a specific planet by its ID"
      operationId: "deletePlanetById"
      tags:
        - "Planets"
      parameters:
        - name: "id"
          in: "path"
          required: true
          description: "ID of the planet to delete"
          schema:
            type: "integer"
      responses:
        '200':
          description: "Planet deleted successfully"

components:
  schemas:
    Planet:
      type: object
      required:
        - nombre
      properties:
        id:
          type: integer
          description: "The unique ID of the planet."
        nombre:
          type: string
          description: "Name of the planet."
        perido_rotacion:
          type: string
          description: "Rotation period of the planet."
        periodo_orbital:
          type: string
          description: "Orbital period of the planet."
        diametro:
          type: string
          description: "Diameter of the planet."
        clima:
          type: string
          description: "Climate of the planet."
        gravedad:
          type: string
          description: "Gravity of the planet."
        terreno:
          type: string
          description: "Terrain of the planet."
        poblacion:
          type: string
          description: "Population of the planet."
        superficie_agua:
          type: string
          description: "Surface water percentage of the planet."
        url_original:
          type: string
          description: "Original URL of the planet from SWAPI."